name: Publish

on:
   push:
      branches: [ master ]

jobs:
   publish:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [14.x]
      steps:
         - uses: actions/checkout@master
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v1
           with:
              node-version: ${{ matrix.node-version }}
         - name: Cache node_modules
           id: cache-modules
           uses: actions/cache@v1
           with:
              path: node_modules
              key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
         - name: Dependencies
           if: steps.cache-modules.outputs.cache-hit != 'true'
           run: yarn
         - run: yarn build:clean
         - name: Publish to NPM
           if: github.ref == 'refs/heads/master'
           uses: mikeal/merge-release@master
           env:
              GITHUB_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
              NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
